//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Servicios.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("VW_EXPEDIENTE_DETALLE", Schema = "dbo")]
    
    public partial class vw_expediente_detalle
    {
    	[Key()]	
    	public int id_movimiento_documento { get; set; }
    	public int id_documento { get; set; }
    	public string numero_expediente { get; set; }
    	public string documento_interno { get; set; }
    	public string fecha_registro { get; set; }
    	public string asunto { get; set; }
    	public string clase_documento { get; set; }
    	public string dependencia_origen { get; set; }
    	public string dependencia_destino { get; set; }
    	public Nullable<int> enviado { get; set; }
    	public Nullable<int> derivado { get; set; }
    	public Nullable<int> finalizado { get; set; }
    }
}
