//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Servicios.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("VW_REQUISITO_TUPA", Schema = "dbo")]
    
    public partial class vw_requisito_tupa
    {
    	[Key()]	
    	public int id_requisito { get; set; }
    	public Nullable<int> numero_requisito { get; set; }
    	public string descripcion_requisito { get; set; }
    	public Nullable<int> id_estado_requisito { get; set; }
    	public string estado_requisito { get; set; }
    	public string id_tipo_requisito { get; set; }
    	public string des_tipo_requisito { get; set; }
    	public Nullable<decimal> uit_requisito { get; set; }
    	public Nullable<decimal> monto { get; set; }
    	public Nullable<int> id_tupa { get; set; }
    	public Nullable<int> id_clase_tupa { get; set; }
    	public string clase_tupa { get; set; }
    	public string descripcion_tupa { get; set; }
    	public Nullable<int> uit_tupa { get; set; }
    	public Nullable<int> codigo_dependencia { get; set; }
    	public string estado_tupa { get; set; }
    	public string des_estado_tupa { get; set; }
    	public Nullable<int> tipo_aprobacion { get; set; }
    	public Nullable<int> numero_tupa { get; set; }
    }
}
