//===================================================================================
// Template T4 for Enum
//===================================================================================
using System;

namespace Prod.STD.Enumerados
{
   
    //[Serializable]
	public enum TIPO_ENUMERADO 
	{
		NONE = 0, 
		TIPO_DE_DOCUMENTO = 10, 
		TIPO_DE_ESPECIALIDAD = 11, 
		ESTADO_DE_DOCUMENTO = 12, 
		ESTADO_DE_EXPEDIENTE_PAS = 13, 
		ORIGEN_DE_DOCUMENTO = 14, 
		TIPO_DE_DOCUMENTO_DE_IDENTIDAD = 15, 
		ESTADO_DE_EXPEDIENTE_COACTIVO = 16, 
		ESTADO_DE_DEPOSITO = 17, 
		TIPO_DE_CARGO = 18, 
		ESTADO_DE_DEUDA = 19, 
		TIPO_DE_PRONUNCIAMIENTO = 20, 
		FORMATO_DE_RCONAS = 21, 
		SENTIDO_DE_PRONUNCIAMIENTO = 22, 
		CAUSALES_DE_DEVOLUCION = 23, 
		CAUSALES_DE_SUSPENSION = 24, 
		TIPO_DE_MEDIDA_CAUTELAR = 25, 
		COBRANZA_PERSUASIVA = 26, 
		PREGUNTA_EXCLUSIVA = 27, 
		TIPO_DE_DOMICILIO = 28, 
		TIPO_DE_FISCALIZACION = 29, 
		OBJETIVO_DE_FISCALIZACION = 30, 
		ESTADO_DE_SESION = 31, 
		ESTADO_DE_RCONAS = 32, 
		TIPO_DE_SECTOR = 33, 
		TIPO_DE_PROCEDENCIA = 34, 
		TIPO_DE_INFRACCION = 35, 
		UNIDAD_FISCALIZADA = 36, 
		TIPO_DE_MATERIAL = 37, 
		TIPO_DE_SANCION = 38, 
		TIPO_UNIDAD = 39, 
		TIPO_DE_ACTIVIDAD_PLANTA = 40, 
		ESTADO_DE_PROCESAMIENTO = 41, 
		ESTADO_DE_ACUMULADO = 42, 
		TIPO_DE_MEDIDA = 43, 
		ESTADO_DE_FISCALIZACION = 44, 
		TIPO_DE_MATERIA = 45, 
		ESTADO_DE_ACTIVIDAD = 46, 
		CALIFICACION_DE_INFRACCION = 47, 
		COBRANZA_CONVENCIONAL = 48, 
		TIPO_DE_ENTIDAD = 49, 
		ESTADO_DE_PREINICIO = 50, 
		MOTIVO_DE_DEVOLUCION = 51, 
		ESTADO_DE_DEMANDA = 52, 
		RESULTADO_DE_PROCESO_JUDICIAL = 53, 
	}   
}
