//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("ANEXO", Schema = "web_tramite")]
    
    public partial class anexo
    {
    	[Key()]	
    	public int ID_ANEXO { get; set; }
    	public int ID_DOCUMENTO { get; set; }
    	public int ID_TIPO_ANEXO { get; set; }
    	public string NUM_DOCUMENTO_ANEXO { get; set; }
    	public int ID_PERSONA_DESTINO { get; set; }
    	public int FOLIOS { get; set; }
    	public string CONTENIDO { get; set; }
    	public string OBSERVACIONES { get; set; }
    	public string USUARIO { get; set; }
    	public System.DateTime AUDIT_MOD { get; set; }
    	public Nullable<int> coddep { get; set; }
    	public string modificado { get; set; }
    	public Nullable<int> ID_PERSONA { get; set; }
    	public Nullable<int> CORRELATIVO { get; set; }
    	public Nullable<int> ID_DOCUMENTO_ADJUNTO { get; set; }
    	public int ESTADO_ADJUNTO { get; set; }
    	public string MOTIVO_ANULACION { get; set; }
    
        public virtual tipo_anexo tipo_anexo { get; set; }
    }
}
