//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("CLASE_DOCUMENTO_INTERNO", Schema = "dbo")]
    
    public partial class clase_documento_interno
    {
        
        public clase_documento_interno()
        {
            this.documento = new HashSet<documento>();
        }
    
    	[Key()]	
    	public int ID_CLASE_DOCUMENTO_INTERNO { get; set; }
    	public string DESCRIPCION { get; set; }
    	public string PROCEDENCIA { get; set; }
    	public string categoria { get; set; }
    
        
        public virtual ICollection<documento> documento { get; set; }
    }
}
