//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("contador", Schema = "web_tramite")]
    
    public partial class contador
    {
    	public int cont { get; set; }
    	public Nullable<int> anio { get; set; }
    	[Key()]	
    	public int ID { get; set; }
    	public string usuario { get; set; }
    	public string hostname { get; set; }
    	public Nullable<System.DateTime> AUDITMOD { get; set; }
    }
}
