//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DAT_DOCUMENTO_LF", Schema = "web_tramite")]
    
    public partial class dat_documento_lf
    {
    	[Key()]	
    	public int ID_LF { get; set; }
    	public Nullable<int> ID_LASERFICHE { get; set; }
    	public string TIPO_DOCLF { get; set; }
    	public Nullable<int> ID_DOCUMENTO { get; set; }
    }
}
