//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DAT_DOCUMENTO_COPIA", Schema = "usr_std")]
    
    public partial class dat_documento_copia
    {
    	[Key()]	
    	public int ID_DOCUMENTO_COPIA { get; set; }
    	public int ID_DOCUMENTO { get; set; }
    	public int CODDEP { get; set; }
    	public int LEIDO { get; set; }
    	public int ESTADO { get; set; }
    	public System.DateTime AUDITCREA { get; set; }
    }
}
