//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("doc_tipo_tratamiento", Schema = "web_tramite")]
    
    public partial class doc_tipo_tratamiento
    {
    	public int id { get; set; }
    	public int id_documento { get; set; }
    	public int id_tipo_tratamiento { get; set; }
    	public Nullable<int> dependencia { get; set; }
    	[Key()]	
    	public int ID_DOC_TIPO_TRATAMIENTO { get; set; }
    }
}
