//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DOCUMENTO_REFERENCIA", Schema = "usr_std")]
    
    public partial class documento_referencia
    {
    	public int ID_DOCUMENTO { get; set; }
    	[Key()]	
    	public int ID_DOCUMENTO_REFERENCIA { get; set; }
    	public string TIPO_HOJA_TRAMITE { get; set; }
    	public string NUMERO_HOJA_TRAMITE { get; set; }
    	public Nullable<bool> FLAG { get; set; }
    	public int ID_HOJA_TRAMITE { get; set; }
    
        public virtual documento documento { get; set; }
    }
}
