//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DOCUMENTO", Schema = "web_tramite")]
    
    public partial class documento
    {
        
        public documento()
        {
            this.documento_adjunto = new HashSet<documento_adjunto>();
            this.documento_depdestino = new HashSet<documento_depdestino>();
            this.documento_referencia = new HashSet<documento_referencia>();
            this.movimiento_documento = new HashSet<movimiento_documento>();
        }
    
    	[Key()]	
    	public int ID_DOCUMENTO { get; set; }
    	public Nullable<int> ID_PERSONA { get; set; }
    	public Nullable<int> ID_TUP { get; set; }
    	public int ID_TIPO_DOCUMENTO { get; set; }
    	public int ID_ESTADO_DOCUMENTO { get; set; }
    	public Nullable<int> ID_CLASE_DOCUMENTO_INTERNO { get; set; }
    	public string NUM_TRAM_DOCUMENTARIO { get; set; }
    	public string INDICATIVO_OFICIO { get; set; }
    	public string ASUNTO { get; set; }
    	public Nullable<int> FOLIOS { get; set; }
    	public string OBSERVACIONES { get; set; }
    	public string FECHA_RECEPCION { get; set; }
    	public string PRIORIDAD { get; set; }
    	public string USUARIO { get; set; }
    	public System.DateTime AUDITMOD { get; set; }
    	public string ESTADO_REQUISITO { get; set; }
    	public string FECHA2 { get; set; }
    	public Nullable<int> coddep { get; set; }
    	public string OBSFIN { get; set; }
    	public string fecha3 { get; set; }
    	public string modificacion { get; set; }
    	public string referencia { get; set; }
    	public string Fecha_Max_Plazo { get; set; }
    	public Nullable<int> v_asesor { get; set; }
    	public Nullable<int> requerimiento { get; set; }
    	public Nullable<int> coddep_responsable { get; set; }
    	public Nullable<int> ESTADO_EXPEDIENTE { get; set; }
    	public Nullable<int> SUJETO_PROCESO_JUDICIAL { get; set; }
    	public string REPORTE_OCURRENCIA { get; set; }
    	public Nullable<int> id_docbak { get; set; }
    	public string clave { get; set; }
    
        public virtual clase_documento_interno clase_documento_interno { get; set; }
        public virtual estado_documento estado_documento { get; set; }
        
        public virtual ICollection<documento_adjunto> documento_adjunto { get; set; }
        
        public virtual ICollection<documento_depdestino> documento_depdestino { get; set; }
        
        public virtual ICollection<documento_referencia> documento_referencia { get; set; }
        
        public virtual ICollection<movimiento_documento> movimiento_documento { get; set; }
    }
}
