//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("finaldoc", Schema = "web_tramite")]
    
    public partial class finaldoc
    {
    	[Key()]	
    	public int id { get; set; }
    	public int id_documento { get; set; }
    	public string observaciones { get; set; }
    	public Nullable<int> coddep { get; set; }
    	public Nullable<int> estado { get; set; }
    	public Nullable<System.DateTime> auditmod { get; set; }
    	public string usuario { get; set; }
    	public string FLAG { get; set; }
    	public Nullable<System.DateTime> audit_reactiva { get; set; }
    	public string observaciones_reactiva { get; set; }
    	public string usuario_reactiva { get; set; }
    }
}
