//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("MOVIMIENTO_DOCUMENTO", Schema = "web_tramite")]
    
    public partial class movimiento_documento
    {
    	[Key()]	
    	public int ID_MOVIMIENTO_DOCUMENTO { get; set; }
    	public int ID_DOCUMENTO { get; set; }
    	public Nullable<int> ID_RUTA_TUPA { get; set; }
    	public int ID_DEPENDENCIA_ORIGEN { get; set; }
    	public int ID_DEPENDENCIA_DESTINO { get; set; }
    	public Nullable<int> ID_OFICIO { get; set; }
    	public Nullable<int> FOLIOS { get; set; }
    	public string OBSERVACIONES { get; set; }
    	public string FECHA_RESPUESTA { get; set; }
    	public System.DateTime AUDIT_MOD { get; set; }
    	public Nullable<System.DateTime> AUDIT_REC { get; set; }
    	public string estado { get; set; }
    	public string avance { get; set; }
    	public int enviado { get; set; }
    	public int derivado { get; set; }
    	public int finalizado { get; set; }
    	public string fecha_plazo { get; set; }
    	public Nullable<int> codigo_trabajador { get; set; }
    	public string fecha_plazo_interno { get; set; }
    	public Nullable<System.DateTime> AUDIT_TRAB_DER { get; set; }
    	public Nullable<System.DateTime> AUDIT_TRAB_REC { get; set; }
    	public string tratamiento { get; set; }
    	public Nullable<int> condicion { get; set; }
    	public string ULTIMO_AVANCE { get; set; }
    
        public virtual documento documento { get; set; }
    }
}
