//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("OBSERVACIONES_REQUISITOS_TRAMITE", Schema = "dbo")]
    
    public partial class observaciones_requisitos_tramite
    {
    	[Key()]	
    	public int ID { get; set; }
    	public Nullable<int> ID_DOCUMENTO { get; set; }
    	public Nullable<int> ID_REQUISITO_TUPA { get; set; }
    	public string OBSERVACIONES { get; set; }
    	public Nullable<int> ESTADO { get; set; }
    }
}
