//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("tipo_resolucion", Schema = "web_tramite")]
    
    public partial class tipo_resolucion
    {
    	[Key()]	
    	public int id { get; set; }
    	public string descripcion { get; set; }
    	public string descrip_completa { get; set; }
    }
}
