//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("TIPO_ANEXO", Schema = "dbo")]
    
    public partial class tipo_anexo
    {
        
        public tipo_anexo()
        {
            this.anexo = new HashSet<anexo>();
        }
    
    	[Key()]	
    	public int ID_TIPO_ANEXO { get; set; }
    	public string DESCRIPCION { get; set; }
    
        
        public virtual ICollection<anexo> anexo { get; set; }
    }
}
