//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("vw_documento_estado", Schema = "web_tramite")]
    
    public partial class vw_documento_estado
    {
    	[Key()]	
    	public int id_documento_estado { get; set; }
    	public int id_documento { get; set; }
    	public Nullable<int> id_anexo { get; set; }
    	public Nullable<System.DateTime> audit_fecha { get; set; }
    	public string user_audit { get; set; }
    	public string ip_audit { get; set; }
    	public string estado { get; set; }
    	public Nullable<int> id_reporte { get; set; }
    	public Nullable<int> numero_reporte { get; set; }
    }
}
