//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("VW_DAT_DEPENDENCIA", Schema = "web_tramite")]
    
    public partial class vw_dat_dependencia
    {
    	[Key()]	
    	public int CODIGO_DEPENDENCIA { get; set; }
    	public string DEPENDENCIA { get; set; }
    	public string SIGLAS { get; set; }
    	public string CONDICION { get; set; }
    	public Nullable<int> ID_TIPO_DEPENDENCIA { get; set; }
    	public string SECCION { get; set; }
    }
}
