//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("VW_DAT_REQUISITO_TUPA", Schema = "web_tramite")]
    
    public partial class vw_dat_requisito_tupa
    {
    	[Key()]	
    	public int ID_REQUISITO { get; set; }
    	public Nullable<int> ID_TUPA { get; set; }
    	public Nullable<int> NUMERO_REQUISITO { get; set; }
    	public string DESCRIPCION { get; set; }
    	public Nullable<int> ESTADO { get; set; }
    	public string ID_TIPO_REQUISITO { get; set; }
    	public Nullable<decimal> VALOR_UIT { get; set; }
    	public Nullable<decimal> MONTO { get; set; }
    }
}
