//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.STD.Datos.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Prod.STD.Datos.Modelo;
    
    public partial class STDDbContext : DbContext
    {
        public STDDbContext()
            : base("name=STDDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anexo> anexo { get; set; }
        public virtual DbSet<movimiento_documento> movimiento_documento { get; set; }
        public virtual DbSet<clase_documento_interno> clase_documento_interno { get; set; }
        public virtual DbSet<vw_dat_clase_tupa> vw_dat_clase_tupa { get; set; }
        public virtual DbSet<vw_dat_dependencia> vw_dat_dependencia { get; set; }
        public virtual DbSet<vw_dat_tupa> vw_dat_tupa { get; set; }
        public virtual DbSet<resolucion> resolucion { get; set; }
        public virtual DbSet<tipo_resolucion> tipo_resolucion { get; set; }
        public virtual DbSet<v_persona> v_persona { get; set; }
        public virtual DbSet<contador> contador { get; set; }
        public virtual DbSet<vw_dat_requisito_tupa> vw_dat_requisito_tupa { get; set; }
        public virtual DbSet<observaciones_requisitos_tramite> observaciones_requisitos_tramite { get; set; }
        public virtual DbSet<estado_documento> estado_documento { get; set; }
        public virtual DbSet<tipo_anexo> tipo_anexo { get; set; }
        public virtual DbSet<vw_dat_trabajador> vw_dat_trabajador { get; set; }
        public virtual DbSet<finaldoc> finaldoc { get; set; }
        public virtual DbSet<dat_contador_interno> dat_contador_interno { get; set; }
        public virtual DbSet<vw_documentos_sitradoc> vw_documentos_sitradoc { get; set; }
        public virtual DbSet<vw_documentos_sitradoc_digitalizacion> vw_documentos_sitradoc_digitalizacion { get; set; }
        public virtual DbSet<vw_documento_estado> vw_documento_estado { get; set; }
        public virtual DbSet<dat_documento_lf> dat_documento_lf { get; set; }
        public virtual DbSet<dat_documento_copia> dat_documento_copia { get; set; }
        public virtual DbSet<dat_reporte_digitalizado> dat_reporte_digitalizado { get; set; }
        public virtual DbSet<vw_documentos_sitradoc_red_digitalizacion> vw_documentos_sitradoc_red_digitalizacion { get; set; }
        public virtual DbSet<vw_listado_reportes_digitalizados> vw_listado_reportes_digitalizados { get; set; }
        public virtual DbSet<vw_listado_reportes_documentos> vw_listado_reportes_documentos { get; set; }
        public virtual DbSet<dat_reporte_documentos> dat_reporte_documentos { get; set; }
        public virtual DbSet<tipo_tratamiento> tipo_tratamiento { get; set; }
        public virtual DbSet<documento_cont> documento_cont { get; set; }
        public virtual DbSet<cuentainterno> cuentainterno { get; set; }
        public virtual DbSet<doc_tipo_tratamiento> doc_tipo_tratamiento { get; set; }
        public virtual DbSet<vw_documentos_sitradoc_red> vw_documentos_sitradoc_red { get; set; }
        public virtual DbSet<documento_adjunto> documento_adjunto { get; set; }
        public virtual DbSet<documento_depdestino> documento_depdestino { get; set; }
        public virtual DbSet<documento_referencia> documento_referencia { get; set; }
        public virtual DbSet<documento> documento { get; set; }
    }
}
